# -*- coding: utf-8 -*-
"""Big Mart Sales Predication.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18KfIfEAwq-bEFhktKbTpVIkNyknZHmhP

Importing The dependenices
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from xgboost import XGBRFRegressor
from sklearn import metrics
import pickle

"""Data collection and Analysis

"""

1# loading the dataset from csv file to a Pandas Dataframe
big_mart_data=pd.read_csv('Train.csv')

1# frist 5 row of the dataframe
big_mart_data.head()

#number of data points and number of features
big_mart_data.shape

#getting some info about the dataset
big_mart_data.info()

"""Categorical Feature:


-Iteam_identifer                                   
-Iteam_fat_content                         
-Iteam_type                             
-Outlet_identifer                        
-Outlet_size                               
-Outlet_Location_Type                       
-Outlet_Type

"""

#checking for missing values
big_mart_data.isnull().sum()

#Handling Missing values
#mean value of "Iteam_weight"
big_mart_data['Item_Weight'].mean()

#filling missing values in iteam_weight column with mean values
big_mart_data['Item_Weight'].fillna(big_mart_data['Item_Weight'].mean(), inplace=True)

#checking for missing values
big_mart_data.isnull().sum()

"""Replacing the missing values in "Outlet_Size" with mode

"""

mode_of_outlet_size=big_mart_data.pivot_table(values='Outlet_Size', columns='Outlet_Type', aggfunc=(lambda x: x.mode()[0]))

print(mode_of_outlet_size)

missing_values=big_mart_data['Outlet_Size'].isnull()

print(missing_values)

big_mart_data.loc[missing_values,'Outlet_Size']=big_mart_data.loc[missing_values,'Outlet_Type'].apply(lambda x: mode_of_outlet_size.loc['Outlet_Size', x])

#checking for missing values
big_mart_data.isnull().sum()

"""## Encoding Categorical Features"""

encoder = LabelEncoder()

for column in ['Item_Fat_Content', 'Item_Type', 'Outlet_Identifier', 'Outlet_Size', 'Outlet_Location_Type', 'Outlet_Type']:
    big_mart_data[column] = encoder.fit_transform(big_mart_data[column])

big_mart_data.head()

"""Data Analysis"""

big_mart_data.describe()

"""Numerical Features

"""

sns.set()

#Iteam weight distribution
plt.figure(figsize=(6,6))
sns.distplot(big_mart_data['Item_Weight'])
plt.show()

#Iteam visiblity distribution
plt.figure(figsize=(6,6))
sns.distplot(big_mart_data['Item_Visibility'])
plt.show()

#Iteam_MRP distribution
plt.figure(figsize=(6,6))
sns.distplot(big_mart_data['Item_MRP'])
plt.show()

#Outlet_Establishment_Year column
plt.figure(figsize=(6,6))
sns.countplot(x='Outlet_Establishment_Year', data=big_mart_data)
plt.show()

#Item_Outlet_Sales distribution
plt.figure(figsize=(6,6))
sns.distplot(big_mart_data['Item_Outlet_Sales'])
plt.show()

"""Categorical Feature"""

#Iteam_Fat_Content column
plt.figure(figsize=(6,6))
sns.countplot(x='Item_Fat_Content', data=big_mart_data)
plt.show()

#Item_Type  column
plt.figure(figsize=(30,6))
sns.countplot(x='Item_Type', data=big_mart_data)
plt.show()

#Outlet_size  column
plt.figure(figsize=(6,6))
sns.countplot(x='Outlet_Size', data=big_mart_data)
plt.title('Outlet_Size Count')
plt.show()

"""Data pre-processing

"""

big_mart_data.head()

big_mart_data['Item_Fat_Content'].value_counts()

big_mart_data.replace({'Item_Fat_Content':{'3':'1','0':'1','4':'2'}}, inplace=True)

big_mart_data['Item_Fat_Content'].value_counts()

"""Level Encoding"""

encoder=LabelEncoder()

big_mart_data['Item_Identifier']=encoder.fit_transform(big_mart_data['Item_Identifier'])
big_mart_data['Item_Fat_Content']=encoder.fit_transform(big_mart_data['Item_Fat_Content'])
big_mart_data['Item_Type']=encoder.fit_transform(big_mart_data['Item_Type'])
big_mart_data['Outlet_Identifier']=encoder.fit_transform(big_mart_data['Outlet_Identifier'])
big_mart_data['Outlet_Size']=encoder.fit_transform(big_mart_data['Outlet_Size'])
big_mart_data['Outlet_Location_Type']=encoder.fit_transform(big_mart_data['Outlet_Location_Type'])
big_mart_data['Outlet_Type']=encoder.fit_transform(big_mart_data['Outlet_Type'])

big_mart_data.head()

"""Splitting features and Target"""

X=big_mart_data.drop(columns='Item_Outlet_Sales',axis=1)
Y=big_mart_data['Item_Outlet_Sales']

print(X)

print(Y)

"""Splitting the data into Training data and testing data"""

X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=2)

print(X.shape,X_train.shape,X_test.shape)

"""Machine Learning Model Training


XGBoost Regressor
"""

regressor=XGBRFRegressor()

regressor.fit(X_train,Y_train)

"""Evalution"""

#prediction on training data
training_data_prediction=regressor.predict(X_train)

#R squared value
r2_train=metrics.r2_score(Y_train,training_data_prediction)

print('R squared value = ',r2_train)

test_data_prediction=regressor.predict(X_test)

r2_test=metrics.r2_score(Y_test,test_data_prediction)

print('R squared value = ',r2_test)
pickle.dump(regressor, open('model.pkl', 'wb'))

print("Model Saved Successfully!")




